# Site Settings
title: "Henry Nguyen"
description: "AI & Robotics Engineer | Master's Student at SJSU"
theme: jekyll-theme-cayman
url: "https://henrynvp.github.io"
baseurl: ""

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
