# Site Settings
title: "Henry Nguyen"
description: "Master's Student in AI @ SJSU | Specializing in AI & Robotics"
theme: jekyll-theme-cayman
url: "https://henrynvp.github.io"
baseurl: ""

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
